import type { Metadata } from "next";
import { Red_Hat_Text, Red_Hat_Display, Montserrat } from "next/font/google";
import "./globals.css";

// Load your fonts
const redHatText = Red_Hat_Text({
  variable: "--font-red-hat-text",
  subsets: ["latin"],
});

const redHatDisplay = Red_Hat_Display({
  variable: "--font-red-hat-display",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${redHatText.variable} 
          $
          ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
